### ISSUE TITLE
Cannot pass build @ nightly 0.13  ;  rustc @ nightly 1.12

### ISSUE THREAD

**Issue by ScottHuangZL** [evanmiller/rust-xls#1]
Cannot pass build @ nightly 0.13  ;  rustc @ nightly 1.12
Report error: Cound not find `types` in `libc`.  Can you take a look? Thanks.

**Comment by evanmiller** [comment]
It appears the C types have moved to std::os::raw

https://doc.rust-lang.org/stable/std/os/raw/

**Comment by evanmiller** [comment]
Fixed in https://github.com/evanmiller/rust-xls/commit/03c9ef6e44d92f3bad94f81edc9ff1d05e949aa0

**Comment by ScottHuangZL** [comment]
src\main.rs:37:9: 37:34 error: unresolved name `std::env::set_exit_status` [E0425]
src\main.rs:37         std::env::set_exit_status(1);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
src\main.rs:37:9: 37:34 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error 
error: Could not compile `xls`.

To learn more, run the command again with --verbose.

Process finished with exit code 101

**Comment by evanmiller** [comment]
Ok try the updated code sample https://github.com/evanmiller/rust-xls/commit/7788e2479956fa440885dc3fd05654ea042e62c8

**Comment by ScottHuangZL** [comment]
note: ld: cannot find -lxlsreader

error: aborting due to previous error 
error: Could not compile `xls`.

**Comment by evanmiller** [comment]
Requires libxls

http://libxls.sourceforge.net/
